### ISSUE TITLE
configure restore_original_auth_params in OIDC plugin 

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway-ui#25]
https://github.com/GluuFederation/gluu-gateway/issues/441

**Comment by ldeveloperl1985** [comment]
Done and docs updated https://gluu.org/docs/gg/4.2/plugin/gluu-openid-connect-uma-pep/#parameters

**Comment by altexy** [comment]
@ldeveloperl1985 

> It use to Handle POST request after OpenID Connect authentication and redirects. Plugin store the request object and after auth plugin will redirect with the same POST requested parameters.

Some notes:
1. It is not possible to redirect to POST - we transform GET request to original URL into saved method/content-related headers/body on the fly.
2. It works not only with POST, but also with PATCH, PUT and DELETE.

So proposed text for `restore_original_auth_params` :
```
Restore original request's method, content-related headers and body after successful redirection from OP. It is useful if original request has methods like POST, PUT, PATCH, DELETE.
```

**Comment by ldeveloperl1985** [comment]
Got it, Thanks @altexy

**Comment by ldeveloperl1985** [comment]
Done
